# Generated by Django 5.2 on 2025-05-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_alter_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
    ]
